version: '3.8'

services:
  postgres:
    image: postgres:14.2-alpine
    container_name: postgres-local
    environment:
      POSTGRES_DB: worktools
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    command: "postgres -c 'max_connections=500'"
    restart: unless-stopped

volumes:
  postgres-data:
