default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["POSTGRES_HOST"] %>
  port: 5432

development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  # macbook settings
  # port: 5434
  # database: worktoolsdb_production_copy
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  port: 5432
  database: worktools_test


development_prod:
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5434
  database: worktoolsdb_production
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

  test:
  <<: *default
  database: worktoolsdb_production
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

production:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

# Guilherme Settings

# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: 5
#   username: gago
#   password: 123456
#   host: localhost

# development:
#   <<: *default
#   database: backup
